"""Application configuration for the WASMBOX backend."""

APP_NAME = "WASMBOX"
APP_VERSION = "0.1.0"
MAX_CODE_LENGTH = 10000
EXECUTION_TIMEOUT_SECONDS = 30
NODE_EXECUTABLE = "node"
PYODIDE_WORKER_PATH = "wasm/worker.mjs"
PYODIDE_TIMEOUT_SECONDS = EXECUTION_TIMEOUT_SECONDS
